### ISSUE TITLE
NativeShell degrades performance compared to custom embedding

### ISSUE THREAD

**Issue by 0xchase** [nativeshell/nativeshell#154]
Hello,

I am in the process of switching from a custom C++ desktop embedder to nativeshell. When I initially made the switch I noticed a significant performance difference (my UI is complex -- it can involve hundreds/thousands of widgets rendered in an interactive viewer). 

To stress test the performance I tried >1000 widgets rendered in an interactive viewer and measured the FPS when panning around. With my original C++ embedding (using glfw on Linux Desktop), it would render at 25-30 FPS. Using nativeshell built with `cargo run --release` I'd get 12-15 FPS, and using nativeshell built with `cargo run` I'd get 8-10 FPS. 

Any idea as to the cause of this? Initially I wondered if it wasn't building AOT correctly. I had also wondered if maybe it was an issue with the nativeshell window widgets causing offscreen elements to take up unnecessary CPU cycles? But I'm speculating, I don't know how nativeshell works internally. 

Anyway, any help is much appreciated.

**Comment by knopp** [comment]
Nativeshell uses internally standard Flutter linux embedder, which is based on Gtk+3. If there is performance degradation, it would be caused by Gtk 3 OpenGL support. As far as I can tell the way OpenGL embedding works in Gtk 3 is that everything renders to an ofscreen framebuffer which is then blitted to GdkWindow opengl context. This extra step might be what is causing the problem degradation.

I'm not sure how far along the glfw embedder is or if it's even being kept up-todate with the official linux embedder.

NativeShell is one layer above the embedder, so it can't directly affect rendering performance.

**Comment by 0xchase** [comment]
Ok thanks for the rapid response. I suppose I'll have to look elsewhere for a solution.

**Comment by knopp** [comment]
The issue of Flutter using Gtk4 (which might have different performance characteristics for embedding flutter using OpenGL or Vulkan) is tracked here https://github.com/flutter/flutter/issues/94804, though It will likely not happen in foreseeable future.
