### ISSUE TITLE
Is the app template only way to use nativeshell? Or can we integrate it into existing Flutter projects

### ISSUE THREAD

**Issue by GroovinChip** [nativeshell/nativeshell#3]
There doesn't seem to be any documentation regarding this, one way or another.

**Comment by knopp** [comment]
You could take relevant parts from the template and add it to your project. That'd be everything rust and cargo related. Also NativeShell needs WindowWidget in the widget hierarchy, but you can make sure to add that on desktop platforms only.

**Comment by knopp** [comment]
The documentation is very scarce indeed, I'm well aware of that :)

**Comment by knopp** [comment]
There's one caveat. This will work as long as you don't require any native flutter plugins on desktop. These are not yet integrated with NativeShell / cargo build. I don't think this shouldn't be much of an issue in practice, since the functionality of NativeShell should cover much of what plugins would normally do. And you can easily call native (rust) code from NativeShell project if this is not enough.

Still it is something I'd want to support eventually.

**Comment by GroovinChip** [comment]
Thanks for your quick response! When you say native flutter plugins, do you mean anything things like url_launcher, firebase, etc?

**Comment by knopp** [comment]
Yes. URL launcher functionality should definitely be covered by NativeShell itself. Firebase is trickier, I'm not even sure the official packages support desktop (maybe just MacOS).

`bitsdojo_window` will not work because the platform plugin (native code) will not be loaded. It also shouldn't be necessary as NativeShell is expected cover all relevant functionality. Right now it is missing things like minimize/maximize methods and window states, but that quite high on my priority list.

**Comment by wilsonowilson** [comment]
@knopp I think external plugin support is really important. What about plugins for local storage like hive, or specifics like native_pdf_view, flutter_tts, device_info et cetera. Would NativeShell cover that? If not, would it even be possible to mix NativeShell and other plugins in the future?

**Comment by knopp** [comment]
Hive is a package. It doesn't have any platform specific code. It should work without any issues. Support for packages with native code (plugins) should be possible, it just wasn't really a priority, since most plugins don't even support desktop platforms yet.

**Comment by wilsonowilson** [comment]
I see. By any chance, do you plan on adding it to the roadmap if the demand for plugin support changes?

**Comment by knopp** [comment]
Definitely. [Added](https://nativeshell.dev/roadmap/).

**Comment by knopp** [comment]
I added issue to track progress of [platform plugin support](https://github.com/nativeshell/nativeshell/issues/6).

**Comment by knopp** [comment]
Closing the issue, adding to custom projects is now described [here](https://matejknopp.com/post/anatomy-of-nativeshell-project/).

**Comment by GroovinChip** [comment]
So do we no longer need to install Rust? Does everything we need come along with the nativeshell package now?

**Comment by knopp** [comment]
You need to install Rust. Nativeshell is written in Rust and uses the Rust package manager (cargo) to build the project.

Installing Rust is [really straightforward](https://www.rust-lang.org/tools/install) though.

The original question was about adding Nativeshell to existing project.

**Comment by GroovinChip** [comment]
Understood, thanks
