### ISSUE TITLE
Menu bar glitch on fullscreen window change

### ISSUE THREAD

**Issue by wilsonowilson** [nativeshell/nativeshell#85]
When swapping between fullscreen windows on macOS, the menubar's title briefly changes to "App" before switching back to the application's actual name.

You can see it happening in this screen recording.

https://user-images.githubusercontent.com/63465656/132126042-c1e5f832-55fd-4805-95f5-43f6268012bd.mov

**Comment by knopp** [comment]
The reason for is this that in NativeShell, there's a menu that can be specified "globally" for entire application (`Menu.setAsAppMenu`), but menu can also be set for individual window (i.e. when using `MenuBar`). When window becomes active, the window associated menu will take over the app menu, when window becomes inactive, the app menu will take over. The problem here is that when switching screen, the window will become active only when the workspace switching finishes. 

Hopefully this should be too difficult to fix. Possible solution would only switch back to app menu when switching to window without window menu, or when closing active window.
